### PR TITLE
Update CMakeLists.txt for installation

### PR DESCRIPTION
**Pull request by lucbv**
While working on a driver example outside of kokkos remote spaces I found out that the core headers are not installed by the library which means users can't use the library.
This PR should fix that issue.

### CODE REVIEW

**Comment by lucbv** [comment]
@janciesko 
You will need this to build the driver code from the gitlab-ex repo

**Comment by lucbv** [comment]
Hum, it looks like the views templated on remote spaces need to implement tools hooks. I am pretty sure this has no correlation with my changes but it might be nice to take care of it none the less.

**Comment by janciesko** [comment]
Retest this please.

**Comment by janciesko** [comment]
@Rombur - I think my comment above didn't trigger CI.

**Comment by janciesko** [comment]
Retest this please

**Comment by janciesko** [comment]
Checked passed, thanks @lucbv, @Rombur

**Review by janciesko — APPROVED** [review]

**Pull request merged**
