### PR TITLE
Use Kokkos master instead develop in the CI

### PR DESCRIPTION
**Pull request by Rombur**

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
What about the latest tagged release instead?

**Comment by Rombur** [comment]
> What about the latest tagged release instead?

Why? What's your problem with using master?

**Comment by dalg24** [comment]
I am still hoping we will eventually change the default branch to develop and get rid of master.

**Comment by janciesko** [comment]
LGTM, thanks

**Review by janciesko — COMMENTED** [review]
Ok

**Review by janciesko — APPROVED** [review]

**Pull request merged**
