### PR TITLE
Reformat the code in line with Kokkos

### PR DESCRIPTION
**Pull request by Rombur**
This PR reformats the code using the same scripts as Kokkos. I've also added a test in the CI that checks the formatting.

### CODE REVIEW

**Comment by Rombur** [comment]
Retest this please

**Comment by Rombur** [comment]
Seems like Github is having problems with Webhooks and so the CI is not triggered.
```
Webhooks is experiencing degraded performance. We are still investigating and will provide an update when we have one.
Posted 34 minutes ago. Mar 23, 2022 - 14:54 UTC
```

**Comment by Rombur** [comment]
OK this is ready for review

**Review by janciesko — APPROVED** [review]
LGTM

**Pull request merged**
